module.exports =  {
  OPEN: 'OPEN',
  FILLED: 'FILLED',
  NEW: 'NEW',
  CANCELED: 'CANCELED',
  BUY: 'BUY',
  SELL: 'SELL',
  SKIPPED: 'SKIPPED',
  LIMIT: 'LIMIT',
  MARKET: 'MARKET',
  STOP_LOSS: 'STOP_LOSS',
  STOP_LOSS_LIMIT: 'STOP_LOSS_LIMIT',
  TAKE_PROFIT: 'TAKE_PROFIT',
  TAKE_PROFIT_LIMIT: 'TAKE_PROFIT_LIMIT',
  LIMIT_MAKER: 'LIMIT_MAKER'
}